export const LOCATIONS = {
  SAN_FRANCISCO: {
    'en': 'San Francisco',
    'jp': 'サンフランシスコ',
    'href': 'sanfrancisco',
    'dates': 'Oct 16',
    'next_location': 'sapporo',
  },
  SAPPORO: {
    'en': 'Sapporo',
    'jp': '札幌',
    'href': 'sapporo',
    'dates': 'Oct 17 - Oct 20',
    'next_location': 'hakodate',
  },
  HAKODATE: {
    'en': 'Hakodate',
    'jp': '函館',
    'href': 'hakodate',
    'dates': 'Oct 20 - Oct 22',
    'next_location': 'aomori',
  },
  AOMORI: {
    'en': 'Aomori',
    'jp': '青森',
    'href': 'aomori',
    'dates': 'Oct 22 - Oct 24',
    'next_location': 'morioka',
  },
  MORIOKA: {
    'en': 'Morioka',
    'jp': '盛岡',
    'href': 'morioka',
    'dates': 'Oct 24 - Oct 26',
    'next_location': 'ishinomaki',
  },
  ISHINOMAKI: {
    'en': 'Ishinomaki',
    'jp': '石巻',
    'href': 'ishinomaki',
    'dates': 'Oct 26 - Oct 28',
    'next_location': 'sendai',
  },
  SENDAI: {
    'en': 'Sendai',
    'jp': '仙台',
    'href': 'sendai',
    'dates': 'Oct 28 - Nov 2',
    'next_location': 'tokyo',
  },
  TOKYO: {
    'en': 'Tokyo',
    'jp': '東京',
    'href': 'tokyo',
    'dates': 'Nov 2 - Nov 7',
    'next_location': 'yokohama',
  },
  YOKOHAMA: {
    'en': 'Yokohama',
    'jp': '横浜',
    'href': 'yokohama',
    'dates': 'Nov 7 - Nov 10',
    'next_location': 'shizuoka',
  },
  SHIZUOKA: {
    'en': 'Shizuoka',
    'jp': '静岡',
    'href': 'shizuoka',
    'dates': 'Nov 10 - Nov 12',
    'next_location': 'nagoya',
  },
  NAGOYA: {
    'en': 'Nagoya',
    'jp': '名古屋',
    'href': 'nagoya',
    'dates': 'Nov 12 - Nov 15',
    'next_location': 'kyoto',
  },
  KYOTO: {
    'en': 'Kyoto',
    'jp': '京都',
    'href': 'kyoto',
    'dates': 'Nov 15 - Nov 20',
    'next_location': 'kobe',
  },
  KOBE: {
    'en': 'Kobe',
    'jp': '神戸',
    'href': 'kobe',
    'dates': 'Nov 20 - Nov 24',
    'next_location': 'hiroshima',
  },
  HIROSHIMA: {
    'en': 'Hiroshima',
    'jp': '広島',
    'href': 'hiroshima',
    'dates': 'Nov 24 - Nov 29',
    'next_location': 'busan',
  },
  BUSAN: {
    'en': 'Busan',
    'jp': '부산',
    'href': 'busan',
    'dates': 'Nov 29 - Dec 1',
    'next_location': 'nara',
  },
  NARA: {
    'en': 'Nara',
    'jp': '奈良',
    'href': 'nara',
    'dates': 'Dec 1 - Dec 4',
    'next_location': 'osaka',
  },
  OSAKA: {
    'en': 'Osaka',
    'jp': '大阪',
    'href': 'osaka',
    'dates': 'Dec 4 - Dec 11',
    'next_location': 'tokyo_two',
  },
  TOKYO_TWO: {
    'en': 'Tokyo (Round 2)',
    'jp': '東京',
    'href': 'tokyo_two',
    'dates': 'Dec 11 - Dec 19',
  },
};